# Generated by Django 4.1.7 on 2023-03-14 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('viewwork', '0006_alter_menu_id_alter_menu_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
